{% set name = "mira-omf" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MiraGeoscience/omf/archive/v{{ version }}.tar.gz
  sha256: 7afbc81476c40e2ec6d8528f74f4f3e247df1b41bceaf8559a63f554bac85c3f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - geoh5_to_omf  = omf.scripts.geoh5_to_omf:main
    - omf_to_geoh5 = omf.scripts.omf_to_geoh5:main

requirements:
  host:
    - pip
    - python >=3.9.0,<3.11
    - poetry-core >=1.0.0
    - setuptools
  run:
    - python >=3.9.0,<3.11
    - geoh5py >=0.9.0,<0.10.0
    - properties >=0.6.0,<0.7.0
    - pypng 0.20220715.*
    - numpy >=1.23.5,<1.24.0
    - six >=1.16.0,<2.0
    - vectormath >=0.2.0,<0.2.1
    

test:
  imports:
    - omf
  commands:
    - pytest tests/version_test.py
    - pip list
  requires:
    - pip
    - pytest
    - tomli
  source_files:
    - tests/version_test.py
    - pyproject.toml
    - README.rst

about:
  home: https://www.mirageoscience.com/mining-industry-software/python-integration/
  summary: 'API library for Open Mining Format, a new standard for mining data backed by the Global Mining Standards & Guidelines Group.'
  description: |
    API library for Open Mining Format, a new standard for mining data backed by the Global Mining Standards & Guidelines Group.

    **Note:**
    This is a fork created by Mira Geoscience for interoperability with the geoh5 file format.

  license: MIT
  license_file:
    - LICENSE
  dev_url: https://github.com/MiraGeoscience/omf

extra:
  recipe-maintainers:
    - SophieCurinier
    - sebhmg
